import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getAuthFromCookies } from "@/lib/auth";
import { format } from "date-fns";

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await getAuthFromCookies();
  if (!auth) return new NextResponse("Unauthorized", { status: 401 });

  const resolvedParams = await params;
  const id = resolvedParams.id;

  // Try to find by employee ID first (when called from employee portal)
  let applicant: any = null;
  let employeeData: { applicantId: string | null; name: string; email: string } | null = null;

  const employee = await prisma.employee.findUnique({
    where: { id },
    select: { applicantId: true, name: true, email: true }
  });

  if (employee?.applicantId) {
    employeeData = employee;
    applicant = await prisma.applicant.findUnique({
      where: { id: employee.applicantId },
      include: { jobPosting: true },
    });
  }

  // Fallback: try direct applicant ID
  if (!applicant) {
    applicant = await prisma.applicant.findUnique({
      where: { id },
      include: { jobPosting: true },
    });
  }

  if (!applicant) {
    // Return a simple HTML page explaining no offer letter is linked
    return new NextResponse(`
      <!DOCTYPE html><html><body style="font-family:sans-serif;padding:40px;text-align:center">
        <h2>Offer Letter Not Available</h2>
        <p>Your offer letter will be generated by HR and made available here. Contact hr@cyberlabsec.tech if you believe this is an error.</p>
      </body></html>
    `, { headers: { "Content-Type": "text/html" } });
  }

  const { searchParams } = new URL(req.url);
  const notes = searchParams.get("notes") || "";
  const date = format(new Date(), "MMMM d, yyyy");
  const candidateName = applicant.fullName || employeeData?.name || "Candidate";
  const candidateEmail = applicant.email || employeeData?.email || "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Offer Letter - ${candidateName}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', -apple-system, sans-serif; background: #f4f4f5; padding: 40px 20px; }
    .page { background: white; max-width: 780px; margin: 0 auto; padding: 60px 72px; box-shadow: 0 10px 40px rgba(0,0,0,0.12); color: #18181b; line-height: 1.7; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #a855f7; padding-bottom: 24px; margin-bottom: 40px; }
    .logo { font-size: 22px; font-weight: 800; color: #a855f7; display: flex; align-items: center; gap: 8px; }
    .date-info { text-align: right; font-size: 13px; color: #71717a; }
    h1 { font-size: 20px; font-weight: 700; margin-bottom: 28px; color: #09090b; }
    p { margin-bottom: 18px; color: #3f3f46; font-size: 15px; }
    strong { color: #09090b; }
    .highlight-box { margin: 28px 0; padding: 20px 24px; background: #faf5ff; border-left: 4px solid #a855f7; border-radius: 0 8px 8px 0; }
    .highlight-box p { color: #581c87; margin: 0; }
    .sig-section { margin-top: 64px; }
    .sig-line { display: inline-block; width: 200px; border-top: 1px solid #09090b; margin-top: 56px; padding-top: 10px; font-weight: 600; font-size: 14px; }
    .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #e4e4e7; font-size: 12px; color: #a1a1aa; text-align: center; }
    @media print { body { background: white; padding: 0; } .page { box-shadow: none; } }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="logo">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
        CyberLabSec
      </div>
      <div class="date-info">
        <div><strong>Issue Date</strong></div>
        <div>${date}</div>
        <div style="margin-top:4px">Offensive Security &amp; Pentesting</div>
      </div>
    </div>

    <p>${candidateName}<br>${candidateEmail}</p>

    <h1>Letter of Offer — ${applicant.jobPosting.title}</h1>

    <p>Dear <strong>${candidateName}</strong>,</p>

    <p>On behalf of the entire CyberLabSec team, we are delighted to formally extend this offer for the position of <strong>${applicant.jobPosting.title}</strong> (${applicant.jobPosting.type}) at CyberLabSec.</p>

    <p>Your performance throughout our competitive selection process — including the AI-proctored technical assessment and comprehensive profile review — was outstanding. We are confident you will make a meaningful contribution to our offensive security operations.</p>

    ${notes ? `
    <div class="highlight-box">
      <p><strong>Personal Note from the CEO:</strong><br>${notes}</p>
    </div>
    ` : ''}

    <p>Upon accepting this offer, you will be onboarded through the <strong>CyberLabSec Employee Portal</strong>, where you will receive your credentials, team assignments, and initial project briefings.</p>

    <p>Please review this letter carefully. By accepting, you agree to abide by all CyberLabSec internal policies and confidentiality agreements that will be provided during onboarding.</p>

    <p>We look forward to having you on the team. Welcome to CyberLabSec.</p>

    <div class="sig-section">
      <p>Sincerely,</p>
      <div class="sig-line">
        CEO &amp; Founder<br>
        <span style="color:#71717a;font-weight:400">CyberLabSec</span>
      </div>
    </div>

    <div class="footer">
      CyberLabSec · Offensive Security &amp; Pentesting · cyberlabsec.tech · contact@cyberlabsec.tech
    </div>
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html" },
  });
}
